"""
The Microsoft Store's 16:9 hero for Vesopa Express: the kiosk, in a restaurant,
showing the real app.

    python tool/make_store_hero.py <scene.jpg> <portrait-menu.png> <out.png>

WHY IT IS PUT TOGETHER RATHER THAN GENERATED

The scene -- a floor-standing kiosk with a card machine, in a bright
restaurant -- was generated by Gemini (tool/gemini_image.py) from a portrait
screenshot of the menu. Gemini drew the room well and the screen badly: it
redrew the app from the reference, with prices that are not the venue's
(Steak & Chips at 72.00), dish names spelt wrong ("Cuesar Salad") and a
button reading "Review eaiter". A Store picture of the app has to be the app,
so the screen is replaced here by the real screenshot (integration_test/
live_meal_test.dart at EXPRESS_LAYOUT=1080x1920 on the test venue), warped
into the screen's four corners.

THE SCREEN'S CORNERS

Measured on the 5504 x 3072 scene by scanning for the black bezel meeting the
lit screen: its left and right edges are vertical (x 3242 and 4234) and its
top and bottom slope, because the kiosk is turned a little towards the camera.
A different scene needs measuring again (--corners).

THE NAME

Set in the app's own lockup -- the Express mark over "Vesopa Express" in
Montserrat ExtraBold, as on the kiosk's setup screen -- in the calm top-left of
the room, clear of the bottom quarter, where the Store lays its own title and
buttons over a hero.
"""

import argparse
import sys
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFilter, ImageFont

sys.path.insert(0, str(Path(__file__).resolve().parent))
from make_icons import INK, render  # noqa: E402

HERE = Path(__file__).resolve().parent.parent
BOLD = HERE / "assets" / "fonts" / "Montserrat-ExtraBold.ttf"
SEMI = HERE / "assets" / "fonts" / "Montserrat-SemiBold.ttf"

# Top-left, top-right, bottom-right, bottom-left, on the 5504 x 3072 scene.
CORNERS = [(3242, 399.75), (4234, 337.75), (4234, 2161.3), (3242, 2122.8)]
OUT_W, OUT_H = 3840, 2160


def perspective_coeffs(dst, src):
    """PIL's PERSPECTIVE data taking points `dst` (output) to `src` (input)."""
    rows, rhs = [], []
    for (x, y), (u, v) in zip(dst, src):
        rows.append([x, y, 1, 0, 0, 0, -u * x, -u * y])
        rows.append([0, 0, 0, x, y, 1, -v * x, -v * y])
        rhs += [u, v]
    return np.linalg.solve(np.array(rows, float), np.array(rhs, float)).tolist()


def grow(quad, px):
    """The quad pushed out by `px`, so no pixel of the drawn screen survives."""
    cx = sum(p[0] for p in quad) / 4
    cy = sum(p[1] for p in quad) / 4
    return [(x + (px if x > cx else -px), y + (px if y > cy else -px)) for x, y in quad]


def screen_on(scene, shot, quad):
    w, h = scene.size
    quad = grow(quad, 3)
    sw, sh = shot.size
    coeffs = perspective_coeffs(quad, [(0, 0), (sw, 0), (sw, sh), (0, sh)])
    warped = shot.convert("RGB").transform((w, h), Image.PERSPECTIVE, coeffs, Image.BICUBIC)

    # Match the room's exposure: the drawn screen's brightness is the camera's
    # idea of a lit screen in that light, and a UI at full white looks pasted on.
    mask_hard = Image.new("L", (w, h), 0)
    ImageDraw.Draw(mask_hard).polygon(quad, fill=255)
    m = np.asarray(mask_hard) > 0
    drawn = np.asarray(scene.convert("L"), float)[m].mean()
    real = np.asarray(warped.convert("L"), float)[m].mean()
    gain = min(1.0, max(0.85, drawn / real))
    arr = np.asarray(warped, float) * gain

    # A faint sheen from the pendant lights, top left to bottom right.
    ys, xs = np.mgrid[0:h, 0:w]
    x0, x1 = min(p[0] for p in quad), max(p[0] for p in quad)
    y0, y1 = min(p[1] for p in quad), max(p[1] for p in quad)
    t = ((xs - x0) / (x1 - x0) + (ys - y0) / (y1 - y0)) / 2
    sheen = np.clip(0.06 * (1 - t), 0, 0.06)[..., None]
    arr = arr * (1 - sheen) + 255 * sheen
    warped = Image.fromarray(arr.clip(0, 255).astype(np.uint8))
    # The camera's own softness, so the screen sits at the same focus as the bezel.
    warped = warped.filter(ImageFilter.GaussianBlur(0.8))

    # Antialiased edge: the polygon drawn at 4x and brought down.
    big = Image.new("L", (w * 2, h * 2), 0)
    ImageDraw.Draw(big).polygon([(x * 2, y * 2) for x, y in quad], fill=255)
    mask = big.resize((w, h), Image.LANCZOS)
    out = scene.copy()
    out.paste(warped, (0, 0), mask)
    return out


def lockup(img):
    """The Express mark over the name, and one line under it, top left."""
    d = ImageDraw.Draw(img)
    left, top = 250, 250

    mark = render(1600, full_bleed=False)
    mark = mark.crop(mark.getbbox())
    mh = 250
    mark = mark.resize((int(mark.width * mh / mark.height), mh), Image.LANCZOS)
    img.paste(mark, (left, top), mark)

    title = ImageFont.truetype(str(BOLD), 168)
    y = top + mh + 70
    d.text((left - 8, y), "Vesopa Express", font=title, fill=INK)

    line = ImageFont.truetype(str(SEMI), 68)
    y += 168 + 56
    d.text((left, y), "Self-order kiosk for Vesopa EPOS", font=line, fill=(58, 64, 50))
    return img


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("scene")
    ap.add_argument("shot")
    ap.add_argument("out")
    ap.add_argument("--corners", help="x,y x,y x,y x,y  (TL TR BR BL) on the scene")
    a = ap.parse_args()
    quad = CORNERS
    if a.corners:
        quad = [tuple(map(float, p.split(","))) for p in a.corners.split()]

    scene = Image.open(a.scene).convert("RGB")
    img = screen_on(scene, Image.open(a.shot), quad)

    # 16:9 from the left: the kiosk stands right of centre and the calm side of
    # the room is the left, so the trim comes off the far left edge.
    w, h = img.size
    keep = round(h * 16 / 9)
    img = img.crop((w - keep, 0, w, h)).resize((OUT_W, OUT_H), Image.LANCZOS)

    lockup(img).save(a.out, optimize=True)
    print(f"{a.out}  {OUT_W}x{OUT_H}")


if __name__ == "__main__":
    main()
